/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




use std::convert::TryFrom;
use schemars::JsonSchema;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct BadMigrateUserPasswordRequest {
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Vec<String>>,
    #[serde(rename = "password_hash", skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<Vec<String>>,
}

impl BadMigrateUserPasswordRequest {
    pub fn new() -> BadMigrateUserPasswordRequest {
        BadMigrateUserPasswordRequest {
            user_id: None,
            password_hash: None,
        }
    }
}


