/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




use std::convert::TryFrom;
use schemars::JsonSchema;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct BadUpdatePasswordRequest {
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<Vec<String>>,
}

impl BadUpdatePasswordRequest {
    pub fn new() -> BadUpdatePasswordRequest {
        BadUpdatePasswordRequest {
            password: None,
        }
    }
}


