/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




use std::convert::TryFrom;
use schemars::JsonSchema;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct CreateOrgResponse {
    #[serde(rename = "org_id")]
    pub org_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateOrgResponse {
    pub fn new(org_id: String, name: String) -> CreateOrgResponse {
        CreateOrgResponse {
            org_id,
            name,
        }
    }
}


