/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




use std::convert::TryFrom;
use schemars::JsonSchema;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct EmailsQuery {
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
}

impl EmailsQuery {
    pub fn new(emails: Vec<String>) -> EmailsQuery {
        EmailsQuery {
            emails,
        }
    }
}


